config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'

  resources :hairs, only: [:index, :show, :new, :create, :destroy] do
    resources :locations, only: [:new, :create]
  end
  resources :locations, only: [:show, :index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hair.rb
class Hair < ApplicationRecord
  COLORS = ["brun", "chatain", "noir", "blond", "blanc", "rouge", "bleu", "roux"]
  TYPES = ["boucle", "raide", "crepu", "ondule"]
  LENGTH = ["ras", "court", "mi-long", "long"]

  belongs_to :user
  has_many :locations, dependent: :destroy
  has_one_attached :photo

  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  validates :color, presence: true
  validates :nature, presence: true
  # validates :quantity, presence: true
  validates :price, presence: true

  validates :color, inclusion: { in: Hair::COLORS }
  validates :nature, inclusion: { in: Hair::TYPES }

  include PgSearch::Model
  pg_search_scope :search_by_nature_and_color,
    against: %i[nature color],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :hair
  belongs_to :user

  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :end_date_after_start_date
  validate :valid_dates

  def total_cost
    length_of_location = (end_date - start_date).to_i
    length_of_location * hair.price
  end

  def total_num_day
    day_of_location = (end_date - start_date).to_i
  end

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if start_date > end_date
      errors.add(:start_date, "can't be after end date")
    end
  end

  def valid_dates
    locations = hair.locations
    data_ranges = locations.map { |loc| loc.start_date..loc.end_date }

    if !(date_included?(data_ranges))
      errors.add(:start_date, "not available")
    end
  end

  def date_included?(data_ranges)
    data_ranges.all? do |une_duree_de_loc|
      une_duree_de_loc.to_a.each do |day|
        return false if (start_date..end_date).include?(day)
      end
    end
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :hairs, dependent: :destroy
  has_many :locations, dependent: :destroy
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  include Pundit

   # Pundit: white-list approach.
   after_action :verify_authorized, except: :index, unless: :skip_pundit?
   after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

    def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address, :phone, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :address, :phone])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/hairs_controller.rb
class HairsController < ApplicationController
  before_action :set_hair, only: [:show, :destroy]
  skip_before_action :authenticate_user!, only: [:index]


  def index
    if params[:hair] && (params[:hair][:nature].present? || params[:hair][:color])
      @hairs = policy_scope(Hair.search_by_nature_and_color("#{params[:hair][:nature]} #{params[:hair][:color]}"))
    else
      @hairs = policy_scope(Hair)
    end
    @hair_colors = %w(blond roux brun chatain noir rouge blanc)
    @hair_top = %w(Chew4 Kahl-Drogo Sulli Robinson Tormund)
  end

  def new
    @hair = Hair.new
    authorize @hair
  end

  def create
    @hair = Hair.new(hair_params)
    @hair.user = current_user
    authorize @hair
    
    if @hair.save
      redirect_to hair_path(@hair)
    else
      render :new
    end
  end

  def show
    @user = current_user
    @location = Location.new
    authorize @hair
  end

  def destroy
    authorize @hair
    @hair.destroy
  end

  private

  def set_hair
    @hair = Hair.find(params[:id])
  end

  def hair_params
    params.require(:hair).permit(:title, :description, :color, :quantity, :hair_length, :status, :price, :nature, :photo)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def new
    @location = Location.new
    @hair = Hair.find(params[:hair_id])
    authorize @location
  end

  def create
    @location = Location.new(location_params)
    authorize @location
    @hair = Hair.find(params[:hair_id])
    @location.hair = @hair
    @location.user = current_user
    if @location.save
      redirect_to location_path(@location)
    else
      redirect_to hair_path(@hair, retry: true)
    end
  end

  def show
    @location = Location.find(params[:id])
    authorize @location
    @hair = @location.hair
  end

  def index
    @locations = policy_scope(Location.where(user: current_user))
  end

  private

  def location_params
    params.require(:location).permit(:start_date, :end_date)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :index]

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hairs/index.html.erb
<div class="container-global">
  <%= simple_form_for :hair, url: hairs_path, method: :get do |f| %>
    <div class="bar_recherche flex">
      <%= f.input :nature,  placeholder: 'Quel type de cheveux souhaitez vous ?', label: "NATURE" %>
      <%= f.input :color,  placeholder: 'Quel couleur souhaitez vous ?', label: "COULEUR" %>
      <%= f.button :submit, "Rechercher", class: "btn-1" %>
    </div>
  <% end %>

  <% if params[:hair].present? %>
    <% if @hairs.empty? %>
      <h3 class="oups border-t-gris">😬 Oups, il n'y a pas de résultats à votre recherche</h3>
      <%= link_to "Retour au menu principal", hairs_path, class: "btn-2 deco-none margin-l-20" %>
    <% else %>
      <div class="hair-card border-t-gris">
        <h3>Résultats de votre recherche</h3>
        <div class="scroll">
          <% @hairs.each do |hair| %>
              <%= render "shared/hair-card", hair: hair %>
            <% end %>
        </div>
        <%= link_to "Retour au menu principal", hairs_path, class: "btn-2 deco-none margin-t-20" %>
      </div>
    <% end %>
  <% else %>
    <div class="border-t-gris color-card">
      <h2>Avec Hairbnb, fini la calvitie </h2>
      <div class="flex">
        <% @hair_colors.each do |color| %>
          <%= render "shared/color_hair_card", color: color %>
        <% end %>
      </div>
    </div>
    <div class="top-card">
      <h2>Les meilleurs cheveulures</h2>
      <h3 id="h3">Découvrez une sélection des chevelures les mieux notées dans le monde</h3>
      <div class="scroll">
        <% @hairs.each do |hair| %>
          <%= render "shared/top_hair_card", hair: hair %>
        <% end %>
      </div>
    </div>
    <div class="hair-card">
      <h3>Classement par dates de mise en ligne</h3>
      <div class="scroll">
        <% @hairs.each do |hair| %>
          <%= render "shared/hair-card", hair: hair %>
        <% end %>
      </div>
    </div>
  <% end %>

</div>

app/views/hairs/new.html.erb
<div class="container-global-new-hair">
  
  <div class="form-container-new-hair">
    <h2>Renseignes ta touffe!</h2>
    <div><%= simple_form_for @hair do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <div class="colors-checkbox">
        <%= f.input :color, as: :radio_buttons, label_method: ->(item) {tag.span item, class: "d-none"}, collection: Hair::COLORS, wrapper: :vertical_collection_inline %>
      </div>
      <div class="natures-checkbox">
        <%= f.input :nature, as: :radio_buttons, label_method: ->(item) {tag.span item, class: "d-none"}, collection: Hair::TYPES, wrapper: :vertical_collection_inline %>
      </div>
      <%= f.input :hair_length, as: :check_boxes, collection: Hair::LENGTH, wrapper: :vertical_collection_inline %>
      <%= f.input :price %>
      <%= f.input :photo, as: :file,
                  required: true %>
       <div class="form-actions">
         <div class="btn-1">
          <%= f.button :submit, "Envoie ta chevelure!" %>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/hairs/show.html.erb
<div class="container-global">
<!-- ========================================================================= -->
  <div class="row">
    <div class="col-12 col-lg-8">
      <div>
        <h1 class="titre size_title"><%= @hair.title %></h1>
      </div>
      <div>
        <div>
          <h2 id="user_name"><span class="graisse size-23"><%= @hair.user.name %></span> te loue ses cheveux </h2>
          <h4 class= "gristresclair p_bottom"><%= @hair.user.address %></h4>
          <h2>pour la modique somme de <span class="graisse"><%= @hair.price %> €.</span></h2>
        </div>
        <div class="show_hair_div">
          <div>
            <div class="color_hair_card" style="background-image: url('<%= image_path "colors/#{@hair.color}.jpg" %>')">
              <div class="car_footer">
                <h4><%= @hair.color %></h4>
              </div>
            </div>
          </div>
          <div>
            <div class="nature_hair_card" style="background-image: url('<%= image_path "nature_hair/#{@hair.nature}.svg" %>')">
              <div class="car_footer">
                <h4><%= @hair.nature %></h4>
              </div>
            </div>
          </div>
          <h3> <span class="graisse"><%= @hair.hair_length %></span> </h3>
        </div>
      </div>
    </div>
    <div class="col-12 col-lg-4">
      <div class="mt-2">
        <!-- <img src="<%#= image_path "Chewbacca.jpg" %>" alt="" class="photo_show" > -->
        <%= cl_image_tag @hair.photo.key, crop: :fill, height: "300",width: "300", class: "photo_show" %>
      </div>
    </div>
  </div>
<!-- ========================================================================= -->
  <div class="show_hair_div2">

    <!-- enfant n°1 -->
    <div class="div_enf1">
      <div class="border-bottom marge_hair">
        <h3><%= @hair.description %></h3>
      </div>

      <div class="border-bottom marge_hair">
        <h3><em style="font-weight: thin;">Soins Particuliers</em></h3>
        <h4>Attendre que la colonne 'soins particuliers' soient seedés et migres dns le modele hair</h4>
      </div>


      <div class="div_button_hair_show">
        <%= link_to "Contacter le propriétaire", "#", class: " btn-2 deco-none color_red_button " %>
        <%= link_to hairs_path, class: " btn-2 deco-none color_red_button" do %>
          <h3 class="margin-none"><i class="fas fa-undo-alt"></i> Toutes les chevelures</h3>
        <% end %>
      </div>
    </div>

    <!-- enfant n°2 -->
    <div class="resa-du-hair" style="border: red 1px solid;">
      <%= @locations_dates %>

    </div>



    <!-- div ou on veut faire apparaitre le calendar -->
    <div class="btn_modal">
      <button type="button" class="btn-1 border-none" data-toggle="modal" data-target="#exampleModal">
        <h2 id="loc_button">Je Loue 🤩</h2>
      </button>

      <div class="calendar">
        <%= simple_form_for([@hair, @location]) do |f| %>
          <%= f.input :start_date, as: :string, required: false, input_html: {id: "range_start"} %>
          <%#= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
          <%#= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
          <%= f.input :end_date, as: :string, required: false, input_html: {id: "secondRangeInput"} %>
          <%= f.button :submit, "Go", class: "btn btn-primary" %>
        <% end %>
      </div>

      <!-- Modal -->
<!--           <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">

            <div class="modal-body form_loc">
              <%#= render "locations/form", hair: @hair, location: @location %>
              ...
            </div>

          </div>
        </div>
      </div> -->
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HairBnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Lora:wght@400;500;700&family=Roboto:wght@100;400;700&display=swap" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

<!-- class="<#% 'img-sign-in-test' if controller_name == 'sessions' && action_name == 'new' %>" -->
  <body >
    <% if user_signed_in? %>
      <%= render "shared/navbar_when_sign_in" %>
    <% else %>
      <%= render "shared/navbar_when_not_sign_in" %>
    <% end %>

    <%= render 'shared/flashes' %>
    <%= yield %>

    <div id="my-footer">
      <ul class="list-inline">
        <li><a href="#"><i class="fab fa-facebook"></i></a></li>
        <li><a href="#"><i class="fab fa-instagram"></i></li>
        <li><a href="#"><i class="fab fa-twitter-square"></i></li>
        <li><a href="#"><i class="fab fa-youtube"></i></li>
      </ul>
    </div>

  </body>
</html>

app/views/locations/_card_location.html.erb
<div class="card-location">
  <% if location.hair.photo.attached? %>
    <div class="radius">
      <%= cl_image_tag location.hair.photo.key, crop: :fill, height: "250", width: "250"%>
    </div>
  <% else %>
      <div class="radius">
       <%= image_tag "Chewbacca.jpg", alt: "alttext" %>
      </div>
  <% end %>
  <div class="enf2">
    <h3> <%= location.hair.user.name %></h3>
    <h3> <%= location.start_date.strftime(' %e %B %Y') %></h3>
    <h3> <%= location.end_date.strftime(' %e %B %Y') %></h3>
    <h3><%= location.total_num_day %> jours</h3>
    <h3> <%= "#{location.total_cost} €" %> </h3>
  </div>
</div>

app/views/locations/_form.html.erb
<div class="container_formulaire">
  <div class="card_formulaire">
    <h3 class="titre_form"> Durée de location :  </h3>
    <%= simple_form_for([@hair, @location]) do |f| %>
      <%= f.input :start_date, as: :string, input_html: {type: :date} %>
      <%= f.input :end_date, as: :string, input_html: {type: :date} %>
      <%= f.submit  'Vérifier la disponibilité', class: "btn btn-danger" %>
    <% end %>
  </div>
</div>

app/views/locations/index.html.erb
<div class="container-global">
  <h2>Mes Locations</h2>
  <% @locations.each do |location| %>
    <%= render 'card_location', location: location %>
  <% end %>
</div>

app/views/locations/new.html.erb
<%= render "form", hair: @hair, location: @location  %>

app/views/locations/show.html.erb
<div class="container-global">

  <div class="row">
    <div class="col-12 col-lg-8">
      <div>
        <h1>
          Cher <%= User.find(@location.user_id).name %>, ta location a bien été validée .
        </h1>
      </div>
      <div class="info_loc">
        <div>
          <h2 id="user_name"><span class="graisse size-23"><%= @hair.user.name %></span> te loue <%= @hair.title %> </h2>
          <h2>au prix de <span class="graisse"><%= @location.total_cost %> €.</span></h2>
          <h2>Du <%= @location.start_date %> au <%= @location.end_date %></h2>
        </div>
        <div class="show_hair_div">
          <div>
            <div class="color_hair_card" style="background-image: url('<%= image_path "colors/#{@hair.color}.jpg" %>')">
              <div class="car_footer">
                <h4><%= @hair.color %></h4>
              </div>
            </div>
          </div>
          <div>
            <div class="nature_hair_card" style="background-image: url('<%= image_path "nature_hair/#{@hair.nature}.svg" %>')">
              <div class="car_footer">
                <h4><%= @hair.nature %></h4>
              </div>
            </div>
          </div>
          <h3> <span class="graisse"><%= @hair.hair_length %></span> </h3>
        </div>
      </div>
    </div>
    <div class="col-12 col-lg-4">
      <div>
        <!-- <img src="<%= image_path "Chewbacca.jpg" %>" alt="" class="photo_show" > -->
        <%= cl_image_tag @hair.photo.key,crop: :fill, height: "300",width: "300", class: "photo_show" %>
      </div>
    </div>
  </div>

  <%= link_to "Contacter le propriétaire", "#", class: " btn-2 deco-none color_red_button marges" %>
  <%= link_to "Voir toutes mes locations", locations_path, class: " btn-2 deco-none color_red_button marges" %>


</div>

app/views/pages/home.html.erb
<div class="img-sign-in">
  <div class="container-global container-home with-bg d-flex">

       <div class="btn-container">
          <%= link_to "Recherchez une chevelure", hairs_path, class: "btn-1" %>
          <h2 id="home_title">Avec Hairbnb, fini la calvitie</h2>
        </div>
        <div class="btn-container">
          <%= link_to "Louez votre chevelure", new_hair_path, class: "btn-1" %>
          <h2 id="home_title">Vos cheveux peuvent faire des heureux </h2>
        </div>
  </div>
</div>

app/views/shared/_color_hair_card.html.erb
<!-- COLOR HAIR CARD -->
<div>
  <div class="color_hair_card" style="background-image: url('<%= image_path "colors/#{color}.jpg" %>')">
    <div class="car_footer">
      <h4>Cheveux <%= color %></h4>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_hair-card.html.erb
<!-- HAIR CARD -->
<%= link_to(hair_path(hair.id))do %>

  <div id="lien_out" class="margin-index">
    <div class="hair_card" style="background-image: url('<%= cl_image_path hair.photo.key %>')">
      <i id="bg" class="fas fa-heart"></i>
      <i class="far fa-heart"></i>
    </div>
    <h3> <%= "#{hair.color.capitalize} | #{hair.nature.capitalize}" %> </h3>
  </div>
<% end %>

app/views/shared/_nature_hair_card.html.erb
<!-- NATURE HAIR CARD -->
<div>
  <div class="nature_hair_card" style="background-image: url('<%= image_path "nature_hair/#{nature}.svg" %>')">
    <div class="car_footer">
      <h4><%= nature %></h4>
    </div>
  </div>
</div>

app/views/shared/_navbar-all.html.erb
<div class="navbar-bg navbar-content">
  <div class="navbar-content w-100">
    <%= link_to "hairbnb", root_path %>
    <div>tgt</div>
    <div class="navbar-content">
      <div class="navbar-content">
        <i class="fas fa-globe mr-2"></i>
        <i class="fas fa-angle-down"></i>
      </div>
      <div class="navbar-content ml-4">
        <i class="fas fa-bars"></i>
        <div class="ml-2">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
              <%= image_tag "Chewbacca.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Louer ma chevelure", new_hair_path, class: "dropdown-item" %>
                <%= link_to "Mes locations", "#", class: "dropdown-item" %>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar_when_not_sign_in.html.erb
<div class="navbar-bg navbar-content d-flex space-between">
   <%= link_to "hairbnb", root_path, class: "logo" %>
   <%= link_to "Sign in", new_user_session_path, class: "btn-1" %>
</div>

app/views/shared/_navbar_when_sign_in.html.erb
<div class="navbar-bg navbar-content">
  <div class="navbar-content w-100">
    <%= link_to "hairbnb", root_path, class: "logo" %>
    <%= link_to(new_hair_path, class: "deco-none") do  %>
      <div class="btn-add-hair">
        <h3><i class="fas fa-plus plus"></i> Louer ma chevelure</h3>
      </div>
    <% end %>
    <div class="navbar-content">
      <div class="navbar-content">
        <i class="fas fa-globe mr-2"></i>
        <i class="fas fa-angle-down"></i>
      </div>
      <div class="navbar-content ml-4 av-hover">
        <i class="fas fa-bars"></i>
        <div class="ml-2">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, :width=>30, :height=>30, :radius=>"max", crop: :thumb, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <% else %>
                <%= image_tag "Chewbacca.jpg",  :width=>30, :height=>30,  class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <% end %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Mes locations", locations_path, class: "dropdown-item" %>
                <%= link_to "Se deconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_photo-display.html.erb
<div class="flex radius-photo">
  <%= cl_image_tag @hair.photo.key, class: "photo-size" %>
  <div class="photo-display photo-size">
    <img src="<%= image_path "Chewbacca.jpg" %>" alt="" class="photo-1 scd-photo-size">
    <img src="<%= image_path "Chewbacca.jpg" %>" alt="" class="photo-2 scd-photo-size">
    <img src="<%= image_path "Chewbacca.jpg" %>" alt="" class="photo-3 scd-photo-size">
    <img src="<%= image_path "Chewbacca.jpg" %>" alt="" class="photo-4 scd-photo-size">
  </div>
</div>

app/views/shared/_top_hair_card.html.erb
<!-- TOP HAIR CARD -->
<%= link_to(hair_path(hair.id))do %>

  <div id="lien_out" class="margin-index">

    <div class="hair_card" style="background-image: url('<%= cl_image_path hair.photo.key %>')">
      <i id="bg" class="fas fa-heart"></i>
      <i class="far fa-heart"></i>
    </div>
    <div class="flex">
      <i class="fas fa-star"></i>
      <h4>5</h4>
      <h4>(398)</h4>
    </div>
    <h3><%= "#{hair.color.capitalize} | #{hair.nature.capitalize}" %></h3>
  </div>
<% end %>